// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABAVC0TBO3aHsjyQum3Rykw4ryDCJd-8k',
    appId: '1:610511961612:web:effca0a87db739d1d6b829',
    messagingSenderId: '610511961612',
    projectId: 'ecommerc-42f3e',
    authDomain: 'ecommerc-42f3e.firebaseapp.com',
    storageBucket: 'ecommerc-42f3e.firebasestorage.app',
    measurementId: 'G-CS7FP2NZVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjy8QQbfAzi09bHenNdlTW-plx15NGWj4',
    appId: '1:610511961612:android:ed578ae6ba70ef1cd6b829',
    messagingSenderId: '610511961612',
    projectId: 'ecommerc-42f3e',
    storageBucket: 'ecommerc-42f3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz8gfZ5GNCXYt03k-ymJx8LZ0U8tx8XXU',
    appId: '1:610511961612:ios:4e2c2b2f6732c374d6b829',
    messagingSenderId: '610511961612',
    projectId: 'ecommerc-42f3e',
    storageBucket: 'ecommerc-42f3e.firebasestorage.app',
    iosBundleId: 'com.example.eStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz8gfZ5GNCXYt03k-ymJx8LZ0U8tx8XXU',
    appId: '1:610511961612:ios:4e2c2b2f6732c374d6b829',
    messagingSenderId: '610511961612',
    projectId: 'ecommerc-42f3e',
    storageBucket: 'ecommerc-42f3e.firebasestorage.app',
    iosBundleId: 'com.example.eStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABAVC0TBO3aHsjyQum3Rykw4ryDCJd-8k',
    appId: '1:610511961612:web:568461ca6fbeacc1d6b829',
    messagingSenderId: '610511961612',
    projectId: 'ecommerc-42f3e',
    authDomain: 'ecommerc-42f3e.firebaseapp.com',
    storageBucket: 'ecommerc-42f3e.firebasestorage.app',
    measurementId: 'G-PZ4Q7HM47Z',
  );
}
